remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: TurboTV
description: Translation Validation for TurboFan

github:
  owner_name: "Programming Systems Lab @ KAIST"
  owner_url: https://prosys.kaist.ac.kr
