(* Generated by scripts/spec2ml.py *)
exception Invalid_opcode

type p1 =
  | Branch
  | ChangeInt32ToTagged
  | CheckedTaggedSignedToInt32
  | StackPointerGreaterThan

type b1 =
  | Call
  | ExternalConstant
  | HeapConstant
  | Int32Constant
  | Int64Constant

type unimpl =
  | Checkpoint
  | EffectPhi
  | End
  | FrameState
  | IfFalse
  | IfTrue
  | LoadStackCheckOffset
  | Merge
  | Parameter
  | Return
  | Start
  | TypedStateValues

type p1p2 = Int32Add | Load
type t = P1 of p1 | B1 of b1 | UNIMPL of unimpl | P1P2 of p1p2 | Empty

let empty = Empty

let of_str str =
  match str with
  | "Branch" -> P1 Branch
  | "ChangeInt32ToTagged" -> P1 ChangeInt32ToTagged
  | "CheckedTaggedSignedToInt32" -> P1 CheckedTaggedSignedToInt32
  | "StackPointerGreaterThan" -> P1 StackPointerGreaterThan
  | "Call" -> B1 Call
  | "ExternalConstant" -> B1 ExternalConstant
  | "HeapConstant" -> B1 HeapConstant
  | "Int32Constant" -> B1 Int32Constant
  | "Int64Constant" -> B1 Int64Constant
  | "Checkpoint" -> UNIMPL Checkpoint
  | "EffectPhi" -> UNIMPL EffectPhi
  | "End" -> UNIMPL End
  | "FrameState" -> UNIMPL FrameState
  | "IfFalse" -> UNIMPL IfFalse
  | "IfTrue" -> UNIMPL IfTrue
  | "LoadStackCheckOffset" -> UNIMPL LoadStackCheckOffset
  | "Merge" -> UNIMPL Merge
  | "Parameter" -> UNIMPL Parameter
  | "Return" -> UNIMPL Return
  | "Start" -> UNIMPL Start
  | "TypedStateValues" -> UNIMPL TypedStateValues
  | "Int32Add" -> P1P2 Int32Add
  | "Load" -> P1P2 Load
  | _ -> raise Invalid_opcode

let to_str opcode =
  match opcode with
  | P1 Branch -> "Branch"
  | P1 ChangeInt32ToTagged -> "ChangeInt32ToTagged"
  | P1 CheckedTaggedSignedToInt32 -> "CheckedTaggedSignedToInt32"
  | P1 StackPointerGreaterThan -> "StackPointerGreaterThan"
  | B1 Call -> "Call"
  | B1 ExternalConstant -> "ExternalConstant"
  | B1 HeapConstant -> "HeapConstant"
  | B1 Int32Constant -> "Int32Constant"
  | B1 Int64Constant -> "Int64Constant"
  | UNIMPL Checkpoint -> "Checkpoint"
  | UNIMPL EffectPhi -> "EffectPhi"
  | UNIMPL End -> "End"
  | UNIMPL FrameState -> "FrameState"
  | UNIMPL IfFalse -> "IfFalse"
  | UNIMPL IfTrue -> "IfTrue"
  | UNIMPL LoadStackCheckOffset -> "LoadStackCheckOffset"
  | UNIMPL Merge -> "Merge"
  | UNIMPL Parameter -> "Parameter"
  | UNIMPL Return -> "Return"
  | UNIMPL Start -> "Start"
  | UNIMPL TypedStateValues -> "TypedStateValues"
  | P1P2 Int32Add -> "Int32Add"
  | P1P2 Load -> "Load"
  | Empty -> ""
