(* Generated by scripts/spec2ml.py *)
exception Invalid_opcode
type kind = 
  | P1
  | B1
  | UNIMPL
  | P1P2
  | P2
  | Empty

type t = 
  (* p1 *)
  | Branch  | ChangeInt32ToTagged  | CheckedTaggedSignedToInt32  | StackPointerGreaterThan
  (* b1 *)
  | Call  | ExternalConstant  | HeapConstant  | Int32Constant  | Int64Constant
  (* unimpl *)
  | Checkpoint  | EffectPhi  | End  | FrameState  | IfFalse  | IfTrue  | LoadStackCheckOffset  | Merge  | Parameter  | Start  | TypedStateValues
  (* p1p2 *)
  | Int32Add  | Load
  (* p2 *)
  | Return
  | Empty

let get_kind opcode = 
  match opcode with
  | Branch  | ChangeInt32ToTagged  | CheckedTaggedSignedToInt32  | StackPointerGreaterThan -> P1
  | Call  | ExternalConstant  | HeapConstant  | Int32Constant  | Int64Constant -> B1
  | Checkpoint  | EffectPhi  | End  | FrameState  | IfFalse  | IfTrue  | LoadStackCheckOffset  | Merge  | Parameter  | Start  | TypedStateValues -> UNIMPL
  | Int32Add  | Load -> P1P2
  | Return -> P2
  | Empty -> Empty 

let empty = Empty

let of_str str = 
  match str with
  | "Branch" ->  Branch
  | "ChangeInt32ToTagged" ->  ChangeInt32ToTagged
  | "CheckedTaggedSignedToInt32" ->  CheckedTaggedSignedToInt32
  | "StackPointerGreaterThan" ->  StackPointerGreaterThan
  | "Call" ->  Call
  | "ExternalConstant" ->  ExternalConstant
  | "HeapConstant" ->  HeapConstant
  | "Int32Constant" ->  Int32Constant
  | "Int64Constant" ->  Int64Constant
  | "Checkpoint" ->  Checkpoint
  | "EffectPhi" ->  EffectPhi
  | "End" ->  End
  | "FrameState" ->  FrameState
  | "IfFalse" ->  IfFalse
  | "IfTrue" ->  IfTrue
  | "LoadStackCheckOffset" ->  LoadStackCheckOffset
  | "Merge" ->  Merge
  | "Parameter" ->  Parameter
  | "Start" ->  Start
  | "TypedStateValues" ->  TypedStateValues
  | "Int32Add" ->  Int32Add
  | "Load" ->  Load
  | "Return" ->  Return
  | _ -> raise Invalid_opcode

let to_str opcode = 
  match opcode with
  |  Branch -> "Branch"
  |  ChangeInt32ToTagged -> "ChangeInt32ToTagged"
  |  CheckedTaggedSignedToInt32 -> "CheckedTaggedSignedToInt32"
  |  StackPointerGreaterThan -> "StackPointerGreaterThan"
  |  Call -> "Call"
  |  ExternalConstant -> "ExternalConstant"
  |  HeapConstant -> "HeapConstant"
  |  Int32Constant -> "Int32Constant"
  |  Int64Constant -> "Int64Constant"
  |  Checkpoint -> "Checkpoint"
  |  EffectPhi -> "EffectPhi"
  |  End -> "End"
  |  FrameState -> "FrameState"
  |  IfFalse -> "IfFalse"
  |  IfTrue -> "IfTrue"
  |  LoadStackCheckOffset -> "LoadStackCheckOffset"
  |  Merge -> "Merge"
  |  Parameter -> "Parameter"
  |  Start -> "Start"
  |  TypedStateValues -> "TypedStateValues"
  |  Int32Add -> "Int32Add"
  |  Load -> "Load"
  |  Return -> "Return"
  | Empty -> failwith "Unreachable"

